// 缺陷记录页面 文件: tableData.js
export default [
  {
    defectName: "风机振动过大",
    taskNumber: "TK-2025001",
    devicePath: "厂房A/风机区",
    deviceName: "主风机-01",
    defectDesc: "运行时噪声异常",
    defectStatus: "未处理",
    defectCategory: "机械故障",
    severityLevel: "严重",
    suggestion: "建议停机检修",
    discoveryTime: "2025-03-01 09:30:00",
    fixTime: "",
    fixPerson: "",
    fixDeadline: "2025-03-05",
    imageUrl: "fengji.jpg"

  },
  {
    defectName: "变频器报警",
    taskNumber: "TK-2025002",
    devicePath: "厂房A/电气室",
    deviceName: "变频器-01",
    defectDesc: "电流波动过大",
    defectStatus: "未处理",
    defectCategory: "电气故障",
    severityLevel: "一般",
    suggestion: "检查变频器线路",
    discoveryTime: "2025-03-02 10:15:00",
    fixTime: "",
    fixPerson: "",
    fixDeadline: "2025-03-06"    ,
    imageUrl: "fengji.jpg"
  },
  {
    defectName: "冷却水泄漏",
    taskNumber: "TK-2025003",
    devicePath: "厂房B/水泵区",
    deviceName: "冷却水泵-02",
    defectDesc: "水泵出口法兰处渗水",
    defectStatus: "未处理",
    defectCategory: "管道故障",
    severityLevel: "严重",
    suggestion: "需停水修复",
    discoveryTime: "2025-03-03 11:20:00",
    fixTime: "",
    fixPerson: "",
    fixDeadline: "2025-03-07",
    imageUrl: "fengji.jpg"
  },
  {
    defectName: "阀门无法完全关闭",
    taskNumber: "TK-2025004",
    devicePath: "厂房B/管道区",
    deviceName: "调节阀-03",
    defectDesc: "关闭时仍有水流",
    defectStatus: "已处理",
    defectCategory: "阀门故障",
    severityLevel: "一般",
    suggestion: "更换阀芯或密封件",
    discoveryTime: "2025-03-04 08:45:00",
    fixTime: "2025-03-05 15:00:00",
    fixPerson: "李师傅",
    fixDeadline: "2025-03-05",
    imageUrl: "fengji.jpg"
  },
  {
    defectName: "温度传感器失灵",
    taskNumber: "TK-2025005",
    devicePath: "厂房A/检测区",
    deviceName: "温度传感器-01",
    defectDesc: "读数与实际温度相差较大",
    defectStatus: "未处理",
    defectCategory: "仪表故障",
    severityLevel: "一般",
    suggestion: "校准或更换传感器",
    discoveryTime: "2025-03-05 13:10:00",
    fixTime: "",
    fixPerson: "",
    fixDeadline: "2025-03-10",
    imageUrl: "fengji.jpg"
  },
  {
    defectName: "配电柜跳闸",
    taskNumber: "TK-2025006",
    devicePath: "厂房A/配电室",
    deviceName: "配电柜-02",
    defectDesc: "高负载时频繁跳闸",
    defectStatus: "未处理",
    defectCategory: "电气故障",
    severityLevel: "严重",
    suggestion: "检查断路器容量",
    discoveryTime: "2025-03-06 09:00:00",
    fixTime: "",
    fixPerson: "",
    fixDeadline: "2025-03-09",
    imageUrl: "fengji.jpg"
  },
  {
    defectName: "传送带老化",
    taskNumber: "TK-2025007",
    devicePath: "厂房C/生产线",
    deviceName: "传送带-01",
    defectDesc: "表面龟裂",
    defectStatus: "未处理",
    defectCategory: "机械故障",
    severityLevel: "一般",
    suggestion: "建议更换皮带",
    discoveryTime: "2025-03-07 10:25:00",
    fixTime: "",
    fixPerson: "",
    fixDeadline: "2025-03-12",
    imageUrl: "fengji.jpg"
  },
  {
    defectName: "轴承温度过高",
    taskNumber: "TK-2025008",
    devicePath: "厂房B/风机区",
    deviceName: "主风机-02",
    defectDesc: "长时间运行后轴承温度异常",
    defectStatus: "已处理",
    defectCategory: "机械故障",
    severityLevel: "严重",
    suggestion: "加注润滑油并检查磨损",
    discoveryTime: "2025-03-08 14:00:00",
    fixTime: "2025-03-09 09:30:00",
    fixPerson: "王工",
    fixDeadline: "2025-03-09",
    imageUrl: "fengji.jpg"
  },
  {
    defectName: "压力表读数不稳",
    taskNumber: "TK-2025009",
    devicePath: "厂房B/锅炉区",
    deviceName: "压力表-03",
    defectDesc: "压力波动时刻度抖动明显",
    defectStatus: "未处理",
    defectCategory: "仪表故障",
    severityLevel: "一般",
    suggestion: "检查压力表管路和接口",
    discoveryTime: "2025-03-09 08:50:00",
    fixTime: "",
    fixPerson: "",
    fixDeadline: "2025-03-11",
    imageUrl: "fengji.jpg"
  },
  {
    defectName: "电机异响",
    taskNumber: "TK-2025010",
    devicePath: "厂房C/生产线",
    deviceName: "电机-01",
    defectDesc: "转速升高时有摩擦声",
    defectStatus: "未处理",
    defectCategory: "机械故障",
    severityLevel: "严重",
    suggestion: "检查轴承与转子",
    discoveryTime: "2025-03-10 11:40:00",
    fixTime: "",
    fixPerson: "",
    fixDeadline: "2025-03-15",
    imageUrl: "fengji.jpg"
  },
  {
    defectName: "管道震动大",
    taskNumber: "TK-2025011",
    devicePath: "厂房B/管道区",
    deviceName: "输送管-04",
    defectDesc: "流量大时出现强烈震动",
    defectStatus: "已处理",
    defectCategory: "管道故障",
    severityLevel: "一般",
    suggestion: "安装防震支架",
    discoveryTime: "2025-03-11 09:20:00",
    fixTime: "2025-03-12 14:00:00",
    fixPerson: "赵工",
    fixDeadline: "2025-03-12",
    imageUrl: "fengji.jpg"
  },
  {
    defectName: "电缆破损",
    taskNumber: "TK-2025012",
    devicePath: "厂房A/配电室",
    deviceName: "主电缆-01",
    defectDesc: "外皮破损，线芯裸露",
    defectStatus: "未处理",
    defectCategory: "电气故障",
    severityLevel: "严重",
    suggestion: "立即停电更换",
    discoveryTime: "2025-03-12 10:10:00",
    fixTime: "",
    fixPerson: "",
    fixDeadline: "2025-03-13",
    imageUrl: "fengji.jpg"
  },
  {
    defectName: "控制系统卡顿",
    taskNumber: "TK-2025013",
    devicePath: "厂房C/控制室",
    deviceName: "PLC-02",
    defectDesc: "数据刷新延迟",
    defectStatus: "未处理",
    defectCategory: "系统故障",
    severityLevel: "一般",
    suggestion: "检查程序和网络",
    discoveryTime: "2025-03-13 15:30:00",
    fixTime: "",
    fixPerson: "",
    fixDeadline: "2025-03-20",
    imageUrl: "fengji.jpg"
  },
  {
    defectName: "冷却水温度偏高",
    taskNumber: "TK-2025014",
    devicePath: "厂房B/水泵区",
    deviceName: "循环水泵-03",
    defectDesc: "出水温度过高",
    defectStatus: "已处理",
    defectCategory: "水泵故障",
    severityLevel: "一般",
    suggestion: "增大冷却水流量",
    discoveryTime: "2025-03-14 09:50:00",
    fixTime: "2025-03-15 10:00:00",
    fixPerson: "陈工",
    fixDeadline: "2025-03-15",
    imageUrl: "fengji.jpg"
  },
  {
    defectName: "风扇叶片断裂",
    taskNumber: "TK-2025015",
    devicePath: "厂房A/风机区",
    deviceName: "排风扇-01",
    defectDesc: "运转时抖动严重",
    defectStatus: "未处理",
    defectCategory: "机械故障",
    severityLevel: "严重",
    suggestion: "停机更换叶片",
    discoveryTime: "2025-03-15 14:10:00",
    fixTime: "",
    fixPerson: "",
    fixDeadline: "2025-03-16",
    imageUrl: "fengji.jpg"
  },
  {
    defectName: "变压器温度报警",
    taskNumber: "TK-2025016",
    devicePath: "厂房A/电气室",
    deviceName: "变压器-02",
    defectDesc: "高负载下温度过高",
    defectStatus: "未处理",
    defectCategory: "电气故障",
    severityLevel: "严重",
    suggestion: "检查散热器及油位",
    discoveryTime: "2025-03-16 10:00:00",
    fixTime: "",
    fixPerson: "",
    fixDeadline: "2025-03-18",
    imageUrl: "fengji.jpg"
  },
  {
    defectName: "油位过低",
    taskNumber: "TK-2025017",
    devicePath: "厂房B/液压站",
    deviceName: "液压泵-01",
    defectDesc: "液压油低于警戒线",
    defectStatus: "已处理",
    defectCategory: "液压故障",
    severityLevel: "一般",
    suggestion: "补充液压油",
    discoveryTime: "2025-03-17 08:00:00",
    fixTime: "2025-03-18 09:00:00",
    fixPerson: "刘工",
    fixDeadline: "2025-03-18",
    imageUrl: "fengji.jpg"
  },
  {
    defectName: "开关柜接触不良",
    taskNumber: "TK-2025018",
    devicePath: "厂房C/配电室",
    deviceName: "开关柜-03",
    defectDesc: "开关合闸时有火花",
    defectStatus: "未处理",
    defectCategory: "电气故障",
    severityLevel: "严重",
    suggestion: "紧固或更换接触器",
    discoveryTime: "2025-03-18 14:45:00",
    fixTime: "",
    fixPerson: "",
    fixDeadline: "2025-03-20",
    imageUrl: "fengji.jpg"
  },
  {
    defectName: "传感器数据偏差",
    taskNumber: "TK-2025019",
    devicePath: "厂房C/检测区",
    deviceName: "位移传感器-02",
    defectDesc: "测量值与实际偏差大",
    defectStatus: "未处理",
    defectCategory: "仪表故障",
    severityLevel: "一般",
    suggestion: "校准或更换传感器",
    discoveryTime: "2025-03-19 11:20:00",
    fixTime: "",
    fixPerson: "",
    fixDeadline: "2025-03-25",
    imageUrl: "fengji.jpg"
  },
  {
    defectName: "风机皮带松弛",
    taskNumber: "TK-2025020",
    devicePath: "厂房A/风机区",
    deviceName: "主风机-03",
    defectDesc: "转速升高时出现打滑",
    defectStatus: "未处理",
    defectCategory: "机械故障",
    severityLevel: "严重",
    suggestion: "调整或更换皮带",
    discoveryTime: "2025-03-20 16:00:00",
    fixTime: "",
    fixPerson: "",
    fixDeadline: "2025-03-22",
    imageUrl: "fengji.jpg"
  }
];
